[package]
name = "post_it"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "post_it"

[dependencies]
axum = "0.3.3"
tokio = { version = "1.13.0", features = ["full"] }

[dev-dependencies]
reqwest = { version = "0.11.6", features = ["json"] }
